### ISSUE TITLE
Use a random spinner while compiling

### ISSUE THREAD

**Issue by mre** [mre/cargo-inspect#13]
Inspired by @killercup.
https://github.com/FGRibreau/spinners

**Comment by mre** [comment]
Also, we should show a christmas tree at christmas time.

**Comment by killercup** [comment]
And play elevator (or Christmas!) music in the background, of course.

**Comment by mre** [comment]
Thinking about [Rust Christmas by Wham!](https://www.youtube.com/watch?v=E8gmARGvPlI).

**Comment by killercup** [comment]
Ah yes, [a classic](https://www.youtube.com/watch?v=Vmzz516cAnw)!
