### ISSUE TITLE
Cargo inspect fails on 2018 edition use syntax

### ISSUE THREAD

**Issue by eddyp** [mre/cargo-inspect#18]
When running `cargo inspect` on a 2018 project using regex crate, it complains about it not using 2015 syntax:

```
eddy@feodora:~/usr/src/rust/c_unit_test_parser$ cargo inspect src/main.rs 
Command failed:
error[E0432]: unresolved import `regex`
 --> src/main.rs:1:5
  |
1 | use regex::Regex;
  |     ^^^^^ maybe a missing `extern crate regex;`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.

eddy@feodora:~/usr/src/rust/c_unit_test_parser$ grep 2018 Cargo.toml 
edition = "2018"
```

**Comment by mre** [comment]
Hum... I have an idea about what's going on. If you call `cargo inspect` on a file, it will call `rustc` directly, which will not resolve any dependencies. If you simply call `cargo inspect` without any arguments, it's gonna call `cargo` and compile the local crate. Can you try that?

**Comment by eddyp** [comment]
> Hum... I have an idea about what's going on. If you call `cargo inspect` on a file, it will call `rustc` directly, which will not resolve any dependencies. If you simply call `cargo inspect` without any arguments, it's gonna call `cargo` and compile the local crate. Can you try that?

Yup, that works, sort of:
```
eddy@feodora:~/usr/src/rust/c_unit_test_parser$ cargo inspect
error: expected type, found `$`
  --> <stdin>:14:6
   |
14 | impl $crate::fmt::Debug for ExpectResult {
   |      ^

Error writing files: parse error
─────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     │ /home/eddy/usr/src/rust/c_unit_test_parser
─────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ #[prelude_import]
   2 │ use ::std::prelude::v1::*;
   3 │ #[macro_use]
   4 │ extern crate std as std;
   5 │ use regex::Regex;
   6 │ use std::fs;
   7 │ use std::io;
   8 │ use std::io::prelude::*;
   9 │ use std::path::Path;
....
```

**Comment by mre** [comment]
Okay, I think that the parse error indicates that `rustfmt` couldn't format the code, in which case we print the error message and continue with the unformatted code. We might wanna hide the error message behind a verbose flag, because it could confuse users. Added #19 to track that. Thanks for reporting. 😃
