### ISSUE TITLE
Support graphviz/dot files

### ISSUE THREAD

**Issue by mre** [mre/cargo-inspect#26]
`rustc` supports graphviz/dot output using the flowgraph flag (see @jonathansty's post [here](https://jonathansteyfkens.com/blog/rust/2019/02/09/exploring-rust.html)):

```
rustc +nightly -Zunpretty=flowgraph=main foo.rs
```

This can already be triggered with cargo-inspect:

```
cargo inspect --unpretty=flowgraph=main
```

Unfortunately, this is just syntax-highlighting the dot-file itself and not showing a pretty graph.
It would be nice to have an option like `cargo inspect --graph`, which renders the dot file as a graph in a new window or as an ASCII representation. We would have to do some research to find a crate which allows this. Help wanted. :)

**Comment by jonathansty** [comment]
I've been having a look at writing ffi bindings to graphviz libraries, mainly `cgraph`.  

I'm at a point now where I've got it building and linking on the msvc toolchain. I haven't tried it yet on linux.  

It's very hacky as I've had to mainly write a `build.rs` to build the correct files and include the correct paths and also define the correct things... 

Next thing I want to try is rewriting the `dot` command of graphviz in rust using the bindings so I can start testing it a bit locally.

**Comment by mre** [comment]
> At this point I think just outputting the graph plain without formatting or either invoking the `dot` command if available would be the easiest and most straightforward way.

Sounds very reasonable. I like the idea of checking for availability of `dot` and if it's not in the `PATH`, we simply print an info message. When setting `--plain`, we could render a textual version. Just my 2 cents.

**Comment by mre** [comment]
Thanks for that. Works beautifully.
