### ISSUE TITLE
Const Function Evaluation

### ISSUE THREAD

**Issue by chuck-flowers** [mre/cargo-inspect#45]
I've enjoyed using cargo inspect to help debug during procedural macro development but I was wondering if it would be possible to make it capable of showing the compile time execution of const functions. I believe this execution happens at the MIR level instead of the HIR level.

The reason I ask is I have a project I'm working on right now where the goal is to compile a builder pattern down to its built output when all of the parameters are known at compile time. I need a tool to prove that it is actually happening though.

**Comment by mre** [comment]
Hi. `cargo-inspect` can print the MIR with a flag if that helps you.
It should be `cargo inspect --unpretty mir`.
If you need deeper inspection, we can try to figure something out.

**Comment by chuck-flowers** [comment]
Okay. I'll try that out and see where that gets me.
