### ISSUE TITLE
Installation fails while building a dep `onig_sys v69.5.0`

### ISSUE THREAD

**Issue by palash25** [mre/cargo-inspect#57]
This is the traceback I get while cargo installing this crate
```
   Compiling darling_macro v0.9.0
error: failed to run custom build command for `onig_sys v69.5.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installedrsNz/release/build/onig_sys-1e6f2f943c42c112/build-script-build` (exit code: 101)
--- stdout
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/palash25/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.3/src/lib.rs:1956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-inspect v0.10.0`, intermediate artifacts can be found at `/tmp/cargo-installedrsNz`

Caused by:
  build failed
```

Looks like that onig_sys needs llvm and clang to be able to build maybe it should be mentioned in the README to have these installed as a pre-requisite?

**Comment by sharkdp** [comment]
The llvm/clang dependency can be avoided by merging updating `cargo-inspect` and `prettyprint` to syntect 4.2.0 (see #56), which depends on an updated version of `onig`/`onig_sys`, that avoids the `bindgen` dependency, which in turn leads needs llvm/clang.

Alternatively, we could move `cargo inspect` from `prettyprint` to `bat` (see comment in `prettyprint` README: https://github.com/mre/prettyprint/), which already depends on syntect 4.2.0.

**Comment by mre** [comment]
@palash25 thanks for the report.

Merged #56 for now, which should fix it.
Can you test the following command and report back?

```
cargo install --git https://github.com/mre/cargo-inspect --branch master
```

@sharkdp thanks for the quick support here; I really appreciate it. In the long run we should move to `bat`. Is the builder pattern already implemented? I was not following closely lately.

**Comment by sharkdp** [comment]
Yes: https://docs.rs/bat/0.15.4/bat/struct.PrettyPrinter.html

Unfortunately, I was not able to make it 100% compatible with `prettyprint` (I definitely tried where possible), but I hope it should be easy to migrate.

**Comment by sharkdp** [comment]
A reason not to upgrade (yet): we will probably need a few more releases until the API stabilizes. I don't expect a lot of work for "clients", but that should be mentioned.

**Comment by mre** [comment]
> A reason not to upgrade (yet): we will probably need a few more releases until the API stabilizes. I don't expect a lot of work for "clients", but that should be mentioned.

Thanks for the heads-up. Will wait a bit and set a reminder to check back in a few weeks then. 👍 
I can already tell that bat's builder offers a few very nice functions that are missing in prettyprint, like `snip()`. Nice work!

**Comment by palash25** [comment]
@mre I had already installed llvm on my machine before reading your comment but I still tried `cargo install --git https://github.com/mre/cargo-inspect --branch master` and it works fine

very cool tool by the way, thanks for building it

**Comment by mre** [comment]
Nice! 0.10.2 released on crates.io. 🎉

**Comment by pravic** [comment]
0.10.2 still fails:

```
Updating cargo-inspect
    Updating crates.io index
  Downloaded cargo-inspect v0.10.2
...
error: failed to run custom build command for `onig_sys v69.5.0`

Caused by:
  process didn't exit successfully: `c:\windows\temp\cargo-installZPmVMM\release\build\onig_sys-4152209514bd3ee8\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', d:\usr\local\rust\cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.53.3\src/lib.rs:1956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-inspect v0.10.2`, intermediate artifacts can be found at ```

**Comment by mre** [comment]
Aaah, I know what's going on. While syntect uses the latest version of onig now, we were still using prettyprint 0.7.2 with an old dependency. Ran a `cargo upgrade` now and checked with `cargo tree` that `bindgen` was indeed absent. Pushed to master now and created a new tag (0.10.3). 
The reason why I didn't notice that was that I had libclang set up for another project on my machine.

@pravic, can you try to `cargo install` again?

**Comment by pravic** [comment]
Now it works, thanks.

**Comment by mre** [comment]
Thanks for the feedback and sorry for the inconvenience. 👍
