### ISSUE TITLE
Add links to documentation

### ISSUE THREAD

**Issue by mre** [mre/cargo-inspect#7]
In some outputs, e.g. the HTML version (#6), we could provide links to common traits and to the docs.

**Comment by balajipcbe** [comment]
Hi, I am interested to help out in adding links to documentation. Can you please provide more info about documentation location,  which html URL to embed?

**Comment by mre** [comment]
Hey @balajipcbe,
we could start by linking all `use std::` statements to the standard library at https://doc.rust-lang.org/std/.

Keep in mind that #6 is not done yet. This means, right now we only have terminal output. There are ways to open links from the command line if they are recognizable by the terminal as such.
So you could add a `--docs` flag and if that is set you could add a comment with the URL to the documentation above each  `use` statement.
Alternatively you could try #6 and add HTML output. Then we could link to the docs directly in there.

**Comment by balajipcbe** [comment]
Thanks for the input. I installed the tool and playing around the with different examples to get familiar with it. Since I am new to github options how do i access the #6 issue?

**Comment by mre** [comment]
My bad. It has moved here: https://github.com/mre/prettyprint/issues/1
Basically, `cargo-inspect` uses `prettyprint` for output formatting. In order to render output as HTML, it would have to be supported by `prettyprint` first. Not sure if you want to tackle that. 
Maybe it's more interesting to start by adding the links as comments about the imports?

**Comment by balajipcbe** [comment]
I looked at prettyprint library module. It produces the formatted output for given source file.
Looks like still it does not produce HTML formatted link yet. Other developer is working to produce the HTML format. Once it is available, we can use prettyprint module. In cargo-inspect, do we want to produce the desugared rust code with HTML links using prettyprint? Is this expected one? Can you give me an example for my better understanding?Thanks
