### ISSUE TITLE
Show memory dropping

### ISSUE THREAD

**Issue by Urhengulas** [mre/cargo-inspect#71]
I'd like `cargo-inspect` to show when `rustc` drops memory (and probably injects calls to `std::mem::drop` or something similar).

Happy to support tackling this, although I'd need some guidance 😸

**Comment by mre** [comment]
Hey @Urhengulas,
interesting idea.
`cargo-inspect` is merely a wrapper around `rustc` and its (partially unstable) config parameters.
Do you know a `rustc` command that produces the desired output? If so we can do it; if not I have no idea how to tackle this. 😉

**Comment by Urhengulas** [comment]
> Hey @Urhengulas,
> interesting idea.
> `cargo-inspect` is merely a wrapper around `rustc` and its (partially unstable) config parameters.
> Do you know a `rustc` command that produces the desired output? If so we can do it; if not I have no idea how to tackle this. 😉 

Hello @mre,
I actually don't, but let's ask around :P
