### ISSUE TITLE
Is this tool working?

### ISSUE THREAD

**Issue by cbiffle** [mre/cargo-inspect#77]
Hi! This looks like a useful tool. Is it expected to work?

I ask because, on current stable/nightly, it prints nothing. Specifically,

```
[cbiffle@coyote elfinject-rs]$ cargo inspect
─────┬───────────────────────────────────────────────────────────────────────────────────
     │ /home/cbiffle/proj/elfinject-rs
─────┼───────────────────────────────────────────────────────────────────────────────────
   1 │ 
─────┴───────────────────────────────────────────────────────────────────────────────────
[cbiffle@coyote elfinject-rs]$
```

bin crates, lib crates, host crates, cross-compiled crates, workspaces, no workspaces -- they all look like that. (Tested on 1.49 stable and a recent nightly.)

I had assumed the crate was not abandoned because of recent commits, but it looks like all commits since ~August are from a bot.

**Comment by mre** [comment]
Hey there @cbiffle,
I'm not actively working on the tool anymore.
You might be better off with [cargo-expand](https://github.com/dtolnay/cargo-expand) for newer projects.
That said, I wasn't aware that the tool wasn't working at the moment.
Just tried it myself and you're right.

Running it with logging enabled gives a hint what's going on:

```❯❯❯ RUST_LOG=debug cargo inspect
⠒ cargo
[2021-02-03T00:11:16Z DEBUG cargo_inspect::hir] error: extra arguments to `rustc` can only be passed to one target, consider filtering
[2021-02-03T00:11:16Z DEBUG cargo_inspect::hir] the package by passing, e.g., `
─────┬─────────────────────────────────────────────────────────────────────────
     │ /path/to/appname
─────┼─────────────────────────────────────────────────────────────────────────
   1 │
─────┴─────────────────────────────────────────────────────────────────────────
```

So we'd have to pass the application name to `rustc` like so:

```
cargo +nightly rustc --bin appname -- -Zunpretty=hir
```

wherever we call `cargo rustc`, like here:
https://github.com/mre/cargo-inspect/blob/682c820a9d7b1a70a33d84fea47e50d966abc8de/src/hir.rs#L42-L49

We'd have to get the appname, though.
An alternative would be to pass `bins`:

```
cargo +nightly rustc --bins -- -Zunpretty=hir
```

It would be easier to implement but print the output of all binaries (which is usually 1). So if it was on me I'd just go with that option. Pull requests appreciated.
Then again I don't expect anyone to implement that and just go with cargo-expand at this point. 😄 
Let me know what you think @cbiffle.

**Comment by akaihola** [comment]
>just go with cargo-expand at this point

Can `cargo-expand` show type inference?
